import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Toaster } from '@/components/ui/toaster'
import { NextAuthProvider } from './AuthProvider'
import { Provider } from '@/store/Provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
	<NextAuthProvider>
    <html lang="en">
			<Provider>
				<body className={inter.className + " min-h-screen"}>
					{children}<Toaster/>
				</body>
			</Provider>
    </html>
	</NextAuthProvider>
  )
}
